USE DATABASE METRICMIND_DB;
USE SCHEMA RAW;
USE WAREHOUSE METRICMIND_WH;

COPY INTO RAW.CUSTOMERS
FROM @RAW.OLIST_STAGE/olist_customers_dataset.csv
FILE_FORMAT = (
    FORMAT_NAME = 'RAW.OLIST_CSV_FORMAT'
)
ON_ERROR = 'ABORT_STATEMENT';

SELECT COUNT(*)
FROM RAW.CUSTOMERS;

SELECT *
FROM RAW.CUSTOMERS
LIMIT 20;

-- Orders

COPY INTO RAW.ORDERS
FROM @RAW.OLIST_STAGE/olist_orders_dataset.csv
FILE_FORMAT = (
    FORMAT_NAME = 'RAW.OLIST_CSV_FORMAT'
)
ON_ERROR = 'ABORT_STATEMENT';


-- Order Items

COPY INTO RAW.ORDER_ITEMS
FROM @RAW.OLIST_STAGE/olist_order_items_dataset.csv
FILE_FORMAT = (
    FORMAT_NAME = 'RAW.OLIST_CSV_FORMAT'
)
ON_ERROR = 'ABORT_STATEMENT';


-- Payments

COPY INTO RAW.ORDER_PAYMENTS
FROM @RAW.OLIST_STAGE/olist_order_payments_dataset.csv
FILE_FORMAT = (
    FORMAT_NAME = 'RAW.OLIST_CSV_FORMAT'
)
ON_ERROR = 'ABORT_STATEMENT';


-- Reviews

COPY INTO RAW.ORDER_REVIEWS
FROM @RAW.OLIST_STAGE/olist_order_reviews_dataset.csv
FILE_FORMAT = (
    FORMAT_NAME = 'RAW.OLIST_CSV_FORMAT'
)
ON_ERROR = 'ABORT_STATEMENT';


-- Products

COPY INTO RAW.PRODUCTS
FROM @RAW.OLIST_STAGE/olist_products_dataset.csv
FILE_FORMAT = (
    FORMAT_NAME = 'RAW.OLIST_CSV_FORMAT'
)
ON_ERROR = 'ABORT_STATEMENT';


-- Sellers

COPY INTO RAW.SELLERS
FROM @RAW.OLIST_STAGE/olist_sellers_dataset.csv
FILE_FORMAT = (
    FORMAT_NAME = 'RAW.OLIST_CSV_FORMAT'
)
ON_ERROR = 'ABORT_STATEMENT';


-- Geolocation

COPY INTO RAW.GEOLOCATION
FROM @RAW.OLIST_STAGE/olist_geolocation_dataset.csv
FILE_FORMAT = (
    FORMAT_NAME = 'RAW.OLIST_CSV_FORMAT'
)
ON_ERROR = 'ABORT_STATEMENT';


-- Category Translation

COPY INTO RAW.CATEGORY_TRANSLATION
FROM @RAW.OLIST_STAGE/product_category_name_translation.csv
FILE_FORMAT = (
    FORMAT_NAME = 'RAW.OLIST_CSV_FORMAT'
)
ON_ERROR = 'ABORT_STATEMENT';